require("andrewzlchen.core.options")
require("andrewzlchen.core.keymaps")
require("andrewzlchen.core.globals")
require("andrewzlchen.core.commands")
require("andrewzlchen.core.autocommands")
require("andrewzlchen.core.idl")
